context:
  version: "0.62.1"

package:
  name: crush
  version: ${{ version }}

source:
  - url: https://github.com/charmbracelet/crush/archive/refs/tags/v${{ version }}.tar.gz
    sha256: fc147b9c26f792f1b2b9334943c7abdb0b5f56cf98d2a391e57531d221d4e79e
    target_directory: src
  - url: https://raw.githubusercontent.com/golang/freetype/master/LICENSE
    sha256: d3ba056adc2b7909e95681deaae397fb37c97ed491a920f491214f07b62c41d0
    target_directory: freetype_license
  - url: https://raw.githubusercontent.com/segmentio/asm/master/LICENSE
    sha256: cca993712df289a5958bdef69031a5dac0f951ac15afeb313f9eeea55ed59443
    target_directory: segmentio_asm_license

build:
  number: 0
  script:
    - cd src
    - go-licenses save . --save_path ../library_licenses --ignore github.com/golang/freetype --ignore github.com/segmentio/asm
    - if: unix
      then:
        - set -x
        - go build -v -o $PREFIX/bin/crush -ldflags="-s -w -X=github.com/charmbracelet/crush/internal/version.Version=${{ version }}"
        - mkdir -p $PREFIX/share/zsh/site-functions $PREFIX/share/bash-completion/completions $PREFIX/share/fish/vendor_completions.d
        - $PREFIX/bin/crush completion zsh > $PREFIX/share/zsh/site-functions/_crush
        - $PREFIX/bin/crush completion bash > $PREFIX/share/bash-completion/completions/crush
        - $PREFIX/bin/crush completion fish > $PREFIX/share/fish/vendor_completions.d/crush.fish
      else: go build -v -o %LIBRARY_BIN%\crush.exe -ldflags="-s -X=github.com/charmbracelet/crush/internal/version.Version=${{ version }}"
requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - go-licenses

tests:
  - script:
      - crush --help
      - crush --version
      - if: unix
        then: crush --version | grep "crush version ${{ version | replace('.', '\\.') }}"
  - package_contents:
      bin:
        - crush
      files:
        - if: unix
          then:
            - share/bash-completion/completions/crush
            - share/fish/vendor_completions.d/crush.fish
            - share/zsh/site-functions/_crush
      strict: true

about:
  homepage: https://github.com/charmbracelet/crush
  summary: The glamourous AI coding agent for your favourite terminal 💘
  description: |
    Your new coding bestie, now available in your favourite terminal.
    Your tools, your code, and your workflows, wired into your LLM of choice.
  license: FSL-1.1-MIT AND MIT
  license_file:
    - src/LICENSE.md
    - library_licenses/
    - freetype_license/LICENSE
    - segmentio_asm_license/LICENSE
  documentation: https://pkg.go.dev/github.com/charmbracelet/crush
  repository: https://github.com/charmbracelet/crush

extra:
  recipe-maintainers:
    - pavelzw
