context:
  version: "0.42.0"

package:
  name: crush
  version: ${{ version }}

source:
  - url: https://github.com/charmbracelet/crush/archive/refs/tags/v${{ version }}.tar.gz
    sha256: ec501481934bcd227695c89603bc499927f98879c1e5e72be1d8f0f84658d119
    target_directory: src
  - url: https://raw.githubusercontent.com/golang/freetype/master/LICENSE
    sha256: d3ba056adc2b7909e95681deaae397fb37c97ed491a920f491214f07b62c41d0
    target_directory: freetype_license

build:
  number: 0
  script:
    - cd src
    - go-licenses save . --save_path ../library_licenses --ignore github.com/golang/freetype
    - if: unix
      then:
        - set -x
        - go build -v -o $PREFIX/bin/crush -ldflags="-s -w -X=github.com/charmbracelet/crush/internal/version.Version=${{ version }}"
      else: go build -v -o %LIBRARY_BIN%\crush.exe -ldflags="-s -X=github.com/charmbracelet/crush/internal/version.Version=${{ version }}"

requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - go-licenses

tests:
  - script:
      - crush --help
      - crush --version
      - if: unix
        then: crush --version | grep "crush version ${{ version | replace('.', '\\.') }}"
  - package_contents:
      bin:
        - crush
      strict: true

about:
  homepage: https://github.com/charmbracelet/crush
  summary: The glamourous AI coding agent for your favourite terminal 💘
  description: |
    Your new coding bestie, now available in your favourite terminal.
    Your tools, your code, and your workflows, wired into your LLM of choice.
  license: FSL-1.1-MIT AND MIT
  license_file:
    - src/LICENSE.md
    - library_licenses/
    - freetype_license/LICENSE
  documentation: https://pkg.go.dev/github.com/charmbracelet/crush
  repository: https://github.com/charmbracelet/crush

extra:
  recipe-maintainers:
    - pavelzw
