context:
  name: crush
  version: "0.2.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/charmbracelet/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: c1f24b8334abc114f0ff4f08a59fa50a52972cd18c23b7eddd1eaa4b044ea390
  target_directory: src

build:
  number: 0
  script:
    - cd src
    - go-licenses save . --save_path ../library_licenses
    - if: unix
      then: go build -v -o $PREFIX/bin/crush -ldflags="-s -w"
      else: go build -v -o %LIBRARY_BIN%\crush.exe -ldflags="-s"

requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - go-licenses

tests:
  - script: crush --help
  - package_contents:
      bin:
        - crush
      strict: true

about:
  homepage: https://github.com/charmbracelet/crush
  summary: The glamourous AI coding agent for your favourite terminal 💘
  description: |
    Your new coding bestie, now available in your favourite terminal.
    Your tools, your code, and your workflows, wired into your LLM of choice.
  license: FSL-1.1-MIT AND MIT
  license_file:
    - src/LICENSE
    - library_licenses/
  documentation: https://pkg.go.dev/github.com/charmbracelet/crush
  repository: https://github.com/charmbracelet/crush

extra:
  recipe-maintainers:
    - pavelzw
